# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: crud.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='crud.proto',
  package='crud',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\ncrud.proto\x12\x04\x63rud\x1a\x1bgoogle/protobuf/empty.proto\"5\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"\x14\n\x06ItemId\x12\n\n\x02id\x18\x01 \x01(\x05\"%\n\x08ItemList\x12\x19\n\x05items\x18\x01 \x03(\x0b\x32\n.crud.Item2\xde\x01\n\x0b\x43rudService\x12$\n\nCreateItem\x12\n.crud.Item\x1a\n.crud.Item\x12$\n\x08ReadItem\x12\x0c.crud.ItemId\x1a\n.crud.Item\x12$\n\nUpdateItem\x12\n.crud.Item\x1a\n.crud.Item\x12(\n\nDeleteItem\x12\x0c.crud.ItemId\x1a\x0c.crud.ItemId\x12\x33\n\tListItems\x12\x16.google.protobuf.Empty\x1a\x0e.crud.ItemListb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='crud.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='crud.Item.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='crud.Item.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='description', full_name='crud.Item.description', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=102,
)


_ITEMID = _descriptor.Descriptor(
  name='ItemId',
  full_name='crud.ItemId',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='crud.ItemId.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=124,
)


_ITEMLIST = _descriptor.Descriptor(
  name='ItemList',
  full_name='crud.ItemList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='items', full_name='crud.ItemList.items', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=126,
  serialized_end=163,
)

_ITEMLIST.fields_by_name['items'].message_type = _ITEM
DESCRIPTOR.message_types_by_name['Item'] = _ITEM
DESCRIPTOR.message_types_by_name['ItemId'] = _ITEMID
DESCRIPTOR.message_types_by_name['ItemList'] = _ITEMLIST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), {
  'DESCRIPTOR' : _ITEM,
  '__module__' : 'crud_pb2'
  # @@protoc_insertion_point(class_scope:crud.Item)
  })
_sym_db.RegisterMessage(Item)

ItemId = _reflection.GeneratedProtocolMessageType('ItemId', (_message.Message,), {
  'DESCRIPTOR' : _ITEMID,
  '__module__' : 'crud_pb2'
  # @@protoc_insertion_point(class_scope:crud.ItemId)
  })
_sym_db.RegisterMessage(ItemId)

ItemList = _reflection.GeneratedProtocolMessageType('ItemList', (_message.Message,), {
  'DESCRIPTOR' : _ITEMLIST,
  '__module__' : 'crud_pb2'
  # @@protoc_insertion_point(class_scope:crud.ItemList)
  })
_sym_db.RegisterMessage(ItemList)



_CRUDSERVICE = _descriptor.ServiceDescriptor(
  name='CrudService',
  full_name='crud.CrudService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=166,
  serialized_end=388,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateItem',
    full_name='crud.CrudService.CreateItem',
    index=0,
    containing_service=None,
    input_type=_ITEM,
    output_type=_ITEM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ReadItem',
    full_name='crud.CrudService.ReadItem',
    index=1,
    containing_service=None,
    input_type=_ITEMID,
    output_type=_ITEM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='UpdateItem',
    full_name='crud.CrudService.UpdateItem',
    index=2,
    containing_service=None,
    input_type=_ITEM,
    output_type=_ITEM,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='DeleteItem',
    full_name='crud.CrudService.DeleteItem',
    index=3,
    containing_service=None,
    input_type=_ITEMID,
    output_type=_ITEMID,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='ListItems',
    full_name='crud.CrudService.ListItems',
    index=4,
    containing_service=None,
    input_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    output_type=_ITEMLIST,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CRUDSERVICE)

DESCRIPTOR.services_by_name['CrudService'] = _CRUDSERVICE

# @@protoc_insertion_point(module_scope)
