name: Python gRPC CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Python
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install grpcio grpcio-tools protobuf pytest

    # Step 4: Generate gRPC files from the .proto file
    - name: Generate gRPC files
      run: |
        python -m grpc_tools.protoc -I=./crud --python_out=./crud --grpc_python_out=./crud crud/crud.proto

    # Step 5: Set PYTHONPATH to include the 'crud' directory
    - name: Set up PYTHONPATH
      run: echo "PYTHONPATH=./crud" >> $GITHUB_ENV

    # Step 6: Run tests with pytest
    - name: Run tests
      run: |
        pytest tests/
